---
- hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
   - name: copy the patch script
     copy: src=ospatch_19042021 dest=/tmp/script1.sh
   - name: set permissions
     file: path=/tmp/script1.sh owner=root group=root mode=0755
   - name: execute the script
     shell: /bin/bash /tmp/script1.sh
   - name: reboot the host
     command: /sbin/reboot
