---
- hosts: all
  tasks:
   - name: mount iso image
     shell: /bin/mount /dev/sr0 /mnt/
   - name: remove repo
     shell: /bin/rm -rf /etc/yum.repos.d/*
   - name: copy repo file
     copy: src=/tmp/rhel69.repo dest=/etc/yum.repos.d/
   - name: httpd install
     yum: name=httpd state=latest
   - name: start service
     service: name=httpd state=started
   - name: perminent the httpd
     service: name=httpd enabled=yes
